### ISSUE TITLE
fee_meta_xdr doesn't have a default decoder when looking at a transaction object

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/laboratory#179]
`fee_meta_xdr` doesn't have any type associated with it in the transactions endpoint: it should be `LedgerEntryChanges`, current workaround is to copy paste its value into the XDR decoder and use `OperationMeta` that happens to be the same type (on the wire).

**Comment by vcarl** [comment]
Is this still a problem? I'm not really sure how to reproduce this, I'm not very familiar with the XDR types.

**Comment by MonsieurNicolas** [comment]
Looks like it's fixed, closing

**Comment by bartekn** [comment]
I can't see `LedgerEntryChanges` in the list.

**Comment by MonsieurNicolas** [comment]
@bartekn 

Mmmm, I think it was fixed. I didn't take a screenshot of the good behavior at the time.

it's still defined in the xdr, this didn't change:
```
typedef LedgerEntryChange LedgerEntryChanges<>;
```

**Comment by lmorgan824** [comment]
Hi,
As of stellar-sdk 6.2.0, latest via npm, this still throws an exception.

const meta = stellar-sdk.xdr.TransactionMeta.fromXDR(fee_meta_xdr, "base64"); 
Error: XDR Read Error: Unknown LedgerEntryChangeType member for value 33078660

Lou

**Comment by janewang** [comment]
This is closed as in v2 we are using XDR to JSON
